AllCops:
  Exclude:
    - vendor/**/*
    - demo/**/*
  TargetRubyVersion: 2.7

require:
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - 'lib/apicraft-rails.rb'

Metrics/MethodLength:
  Max: 75

Layout/LineLength:
  Exclude:
    - 'apicraft-rails.gemspec'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/apicraft/middlewares/mocker.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/apicraft/mocker/any_of.rb'
    - 'lib/apicraft/middlewares/mocker.rb'