openapi: 3.0.0
info:
  title: Product Array API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductArray'
components:
  schemas:
    ProductArray:
      type: array
      items:
        type: object
        properties:
          product_id:
            type: integer
            minimum: 1000
          quantity:
            type: integer
            minimum: 1
        required:
          - product_id
          - quantity
      minItems: 1
      description: An array schema where each item is an object with product details.
